services:
  app:
    image: shinsenter/php:8.4-fpm-apache
    ports:
      - "8080:80"
    environment:
      APP_PATH: /app
      DOCUMENT_ROOT: public
    volumes:
      - ./:/app
    depends_on:
      - db

  db:
    image: mariadb:11
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: ci4
      MARIADB_USER: ci4
      MARIADB_PASSWORD: ci4
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db
      PMA_USER: ci4
      PMA_PASSWORD: ci4
    depends_on:
      - db

volumes:
  dbdata: